---

- name: Install dependencies
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7'

- name: Install dependencies
  yum:
    name: python3-libselinux
    state: present
  when: ansible_distribution_major_version == '8'

# Add all public keys placed in the "files" directory
- name: Deploy SSH keys
  authorized_key:
    user: root
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
    - "*.pub"
