---
# Add all public keys placed in the "files" directory
- name: Deploy SSH keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "*.pub"
