---
- name: Install RHV agent for virtual machines (RHEL 6)
  include: rhv_guest_agent_6.yml
  when: ansible_virtualization_type == "RHEV" and ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"

- name: Install RHV agent for virtual machines (RHEL 7)
  include: rhv_guest_agent_7.yml
  when: ansible_virtualization_type == "RHEV" and ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
