---

- name: Install RHEL 6 guest agent
  yum:
    name: ovirt-guest-agent-common
    enablerepo: rhel-6-server-rhv-4-agent-rpms
    state: present

- name: Start RHEL 6 guest agents
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ovirt-guest-agent
    - qemu-ga
